name: Stage
on:
  push:
    branches:
      - dynamic

permissions:
  contents: read
  packages: read

jobs:
  process:
    name: Push to Modyo Stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/
          scope: '@modyo-dynamic'
      - name: Install @modyo/cli
        run: npm install -g "@modyo/cli@^3.1.27"
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build package
        run: npm run build
        env:
          MODYO_DISABLE_LIQUID_REGEX: ${{ secrets.DISABLE_LIQUID_REGEX }}
          MODYO_BUILD_DIRECTORY: ${{ secrets.BUILD_DIRECTORY }}
      - name: Push to modyo site EN
        run: npm run push "$MODYO_WIDGET_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This gets generated automatically
          MODYO_ACCOUNT_URL: ${{secrets.ACCOUNT_URL}}
          MODYO_VERSION: ${{secrets.VERSION}}
          MODYO_TOKEN: ${{secrets.TOKEN}}
          MODYO_SITE_ID: ${{secrets.STAGE_SITE_ID_EN}}
          MODYO_WIDGET_NAME: ${{secrets.WIDGET_NAME}}
          MODYO_BUILD_DIRECTORY: ${{secrets.BUILD_DIRECTORY}}
          MODYO_DISABLE_LIQUID_REGEX: ${{secrets.DISABLE_LIQUID_REGEX}}
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    needs: process
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
