name: Use build and publish

on:
  push:
    branches:
      - master

jobs:
  use-build-and-publish:
    if: ${{ github.event.repository.is_template == false }}
    uses: dynamic-framework/.github/.github/workflows/build-and-publish-retail.yml@main
    secrets: inherit